mutation SetStatus($electionId: ID!, $status: ElectionStatus!) {
  setStatus(input: { electionId: $electionId, status: $status }) {
    election {
      id
      name
      description
      createdBy {
        id
        email
      }
      candidates {
        id
        name
        description
      }
      status
      statusTransitions {
        on
        status
      }
      results {
        winner {
          id
          name
        }
      }
    }
  }
}
